"""Official 2025 T1 and TP-1 main-return labels.

Labels and applicability notes are transcribed from the published 2025
CRA 5005-R E and Revenu Quebec TP-1.D-V forms. Keep this module in sync
with coverage_2025.py when those official forms or supported lines change.
"""

from __future__ import annotations

LINE_LABELS_2025 = {('T1', '10100'): {'applicability': 'T4 employment income exists; otherwise 0',
                   'label': 'Employment income'},
 ('T1', '10105'): {'applicability': 'T4 exempt volunteer amount exists',
                   'label': 'Tax-exempt income for emergency-services volunteers'},
 ('T1', '10120'): {'applicability': 'T4 box 42 exists',
                   'label': 'Commissions included on line 10100'},
 ('T1', '10130'): {'applicability': 'Employee contributions support the permitted adjustment',
                   'label': 'Wage-loss replacement plan contributions'},
 ('T1', '10400'): {'applicability': 'Other employment income described in the guide exists',
                   'label': 'Other employment income'},
 ('T1', '11300'): {'applicability': 'T4A(OAS) benefit exists', 'label': 'Old Age Security pension'},
 ('T1', '11400'): {'applicability': 'T4A(P) benefit exists', 'label': 'CPP or QPP benefits'},
 ('T1', '11410'): {'applicability': 'T4A(P) disability component exists',
                   'label': 'Disability benefits included on line 11400'},
 ('T1', '11500'): {'applicability': 'Eligible pension/annuity income exists',
                   'label': 'Other pensions and superannuation'},
 ('T1', '11600'): {'applicability': 'Joint T1032 election applies',
                   'label': 'Elected split-pension amount'},
 ('T1', '11700'): {'applicability': 'RC62 benefit exists', 'label': 'Universal child care benefit'},
 ('T1', '11701'): {'applicability': 'Taxpayer elects and qualifies to designate line 11700',
                   'label': 'UCCB amount designated to a dependant'},
 ('T1', '11900'): {'applicability': 'T4E benefits exist',
                   'label': 'Employment Insurance and other benefits'},
 ('T1', '11905'): {'applicability': 'T4E qualifying component exists',
                   'label': 'Maternity/parental/PPIP benefits included on line 11900'},
 ('T1', '12000'): {'applicability': 'T3/T5 dividend exists',
                   'label': 'Taxable dividends from Canadian corporations'},
 ('T1', '12010'): {'applicability': 'Non-eligible dividend component exists',
                   'label': 'Taxable non-eligible dividends included on line 12000'},
 ('T1', '12100'): {'applicability': 'Interest/investment slip or accrued income exists',
                   'label': 'Interest and other investment income'},
 ('T1', '12200'): {'applicability': 'T5013/partnership amount exists',
                   'label': 'Net partnership income: limited or non-active partners'},
 ('T1', '12500'): {'applicability': 'T4A box 131 exists',
                   'label': 'Registered disability savings plan income'},
 ('T1', '12599'): {'applicability': 'Rental activity exists', 'label': 'Gross rental income'},
 ('T1', '12600'): {'applicability': 'Rental activity exists; calculate from T776',
                   'label': 'Net rental income'},
 ('T1', '12700'): {'applicability': 'Disposition or capital-gain slip exists',
                   'label': 'Taxable capital gains'},
 ('T1', '12799'): {'applicability': 'Support was received',
                   'label': 'Total support payments received'},
 ('T1', '12800'): {'applicability': 'Line 12799 includes taxable support',
                   'label': 'Taxable support payments received'},
 ('T1', '12900'): {'applicability': 'T4RSP income exists', 'label': 'RRSP income'},
 ('T1', '12905'): {'applicability': 'T4FHSA taxable withdrawal exists',
                   'label': 'Taxable FHSA income'},
 ('T1', '12906'): {'applicability': 'Other taxable FHSA amount exists',
                   'label': 'Other FHSA income'},
 ('T1', '13000'): {'applicability': 'Income assigned to line 13000 exists, including RESP EAP at '
                                    'T4A box 042',
                   'label': 'Other income'},
 ('T1', '13010'): {'applicability': 'Ordinary award exceeds the applicable '
                                    'enrolment/part-time/basic exemption, or another supported '
                                    'award rule applies',
                   'label': "Taxable scholarships, fellowships, bursaries and artists' project "
                            'grants'},
 ('T1', '13499'): {'applicability': 'Business activity exists',
                   'label': 'Gross / net business income'},
 ('T1', '13500'): {'applicability': 'Business activity exists',
                   'label': 'Gross / net business income'},
 ('T1', '13699'): {'applicability': 'Professional activity exists',
                   'label': 'Gross / net professional income'},
 ('T1', '13700'): {'applicability': 'Professional activity exists',
                   'label': 'Gross / net professional income'},
 ('T1', '13899'): {'applicability': 'Commission business activity exists',
                   'label': 'Gross / net commission income'},
 ('T1', '13900'): {'applicability': 'Commission business activity exists',
                   'label': 'Gross / net commission income'},
 ('T1', '14099'): {'applicability': 'Farming activity exists',
                   'label': 'Gross / net farming income'},
 ('T1', '14100'): {'applicability': 'Farming activity exists',
                   'label': 'Gross / net farming income'},
 ('T1', '14299'): {'applicability': 'Fishing activity exists',
                   'label': 'Gross / net fishing income'},
 ('T1', '14300'): {'applicability': 'Fishing activity exists',
                   'label': 'Gross / net fishing income'},
 ('T1', '14400'): {'applicability': 'T5007 amount exists',
                   'label': "Workers' compensation benefits"},
 ('T1', '14500'): {'applicability': 'T5007 amount exists', 'label': 'Social assistance payments'},
 ('T1', '14600'): {'applicability': 'T4A(OAS) supplement exists',
                   'label': 'Net federal supplements'},
 ('T1', '14700'): {'applicability': 'Always: sum 14400–14600', 'label': 'Benefits total'},
 ('T1', '15000'): {'applicability': 'Always: sum all applicable income lines',
                   'label': 'Total income'},
 ('T1', '20600'): {'applicability': 'T4 box 52/T4A box 034 exists; information line',
                   'label': 'Pension adjustment'},
 ('T1', '20700'): {'applicability': 'T4 box 20/T4A box 032 or supported receipt exists',
                   'label': 'Registered pension plan deduction'},
 ('T1', '20800'): {'applicability': 'Deductible RRSP contribution is claimed through Schedule 7',
                   'label': 'RRSP deduction'},
 ('T1', '20805'): {'applicability': 'Deductible FHSA contribution is claimed through Schedule 15',
                   'label': 'FHSA deduction'},
 ('T1', '20810'): {'applicability': 'PRPP receipt has employer contribution; information line',
                   'label': 'PRPP employer contributions'},
 ('T1', '21000'): {'applicability': 'Joint T1032 election applies',
                   'label': 'Elected split-pension deduction'},
 ('T1', '21200'): {'applicability': 'T4 box 44/receipt exists and qualifies',
                   'label': 'Union, professional or like dues'},
 ('T1', '21300'): {'applicability': 'RC62 repayment exists', 'label': 'UCCB repayment'},
 ('T1', '21400'): {'applicability': 'Eligible expenses exist and T778 applies',
                   'label': 'Child-care expenses'},
 ('T1', '21500'): {'applicability': 'Eligible supports exist and T929 applies',
                   'label': 'Disability supports deduction'},
 ('T1', '21699'): {'applicability': 'Qualifying BIL event exists',
                   'label': 'Gross / allowable business investment loss'},
 ('T1', '21700'): {'applicability': 'Qualifying BIL event exists',
                   'label': 'Gross / allowable business investment loss'},
 ('T1', '21900'): {'applicability': 'Eligible move exists and T1-M applies',
                   'label': 'Moving expenses'},
 ('T1', '21999'): {'applicability': 'Support was paid; deductible component follows support rules',
                   'label': 'Total / deductible support paid'},
 ('T1', '22000'): {'applicability': 'Support was paid; deductible component follows support rules',
                   'label': 'Total / deductible support paid'},
 ('T1', '22100'): {'applicability': 'Qualifying investment expense exists',
                   'label': 'Carrying charges, interest and other expenses'},
 ('T1', '22200'): {'applicability': 'Schedule 8/RC381 produces a deductible base contribution',
                   'label': 'CPP/QPP deduction on self-employment and other earnings'},
 ('T1', '22215'): {'applicability': 'Schedule 8/RC381 produces enhanced contribution',
                   'label': 'Enhanced CPP/QPP contributions on employment'},
 ('T1', '22300'): {'applicability': 'Schedule 10 produces deductible amount',
                   'label': 'PPIP premiums on self-employment'},
 ('T1', '22400'): {'applicability': 'T1229 amount exists',
                   'label': 'Exploration and development expenses'},
 ('T1', '22900'): {'applicability': 'Eligible employment expense and required declaration/form '
                                    'exist',
                   'label': 'Other employment expenses'},
 ('T1', '23100'): {'applicability': 'T1223 eligibility exists',
                   'label': 'Clergy residence deduction'},
 ('T1', '23200'): {'applicability': 'A guide-authorized other deduction exists',
                   'label': 'Other deductions'},
 ('T1', '23300'): {'applicability': 'Always: sum deduction lines', 'label': 'Total deductions'},
 ('T1', '23400'): {'applicability': 'Always: line 15000 less 23300',
                   'label': 'Net income before adjustments'},
 ('T1', '23500'): {'applicability': 'EI/OAS/supplement repayment threshold applies; otherwise '
                                    'explicit 0',
                   'label': 'Social benefits repayment'},
 ('T1', '23600'): {'applicability': 'Always: non-negative result after line 23500 for return '
                                    'presentation',
                   'label': 'Net income'},
 ('T1', '24400'): {'applicability': 'T4 box 43 qualifying amount exists',
                   'label': 'Canadian Armed Forces personnel and police deduction'},
 ('T1', '24900'): {'applicability': 'T4 boxes 39/41/91/92 or T1212 amount exists',
                   'label': 'Security options deductions'},
 ('T1', '25000'): {'applicability': 'Line 14700/14600 rule or Federal Worksheet produces amount',
                   'label': 'Other payments deduction'},
 ('T1', '25100'): {'applicability': 'Available prior-year loss is claimed',
                   'label': 'Limited partnership losses of other years'},
 ('T1', '25200'): {'applicability': 'Available prior-year loss is claimed',
                   'label': 'Non-capital losses of other years'},
 ('T1', '25300'): {'applicability': 'Available prior-year loss is claimed',
                   'label': 'Net capital losses of other years'},
 ('T1', '25395'): {'applicability': 'T2048 applies',
                   'label': 'Capital gains deduction for qualifying business '
                            'transfers/conversions'},
 ('T1', '25400'): {'applicability': 'T657 applies', 'label': 'Capital gains deduction'},
 ('T1', '25500'): {'applicability': 'T2222 applies', 'label': 'Northern residents deductions'},
 ('T1', '25600'): {'applicability': 'Guide-authorized deduction exists',
                   'label': 'Additional deductions'},
 ('T1', '25700'): {'applicability': 'Always: sum 24400–25600',
                   'label': 'Total taxable-income deductions'},
 ('T1', '26000'): {'applicability': 'Always: max(23600 less 25700, 0)', 'label': 'Taxable income'},
 ('T1', '30000'): {'applicability': 'Always; amount depends on line 23600',
                   'label': 'Basic personal amount'},
 ('T1', '30100'): {'applicability': 'Born in 1960 or earlier; worksheet limits apply',
                   'label': 'Age amount'},
 ('T1', '30300'): {'applicability': 'Schedule 5 eligibility exists',
                   'label': 'Spouse or common-law partner amount'},
 ('T1', '30400'): {'applicability': 'Schedule 5 eligibility exists',
                   'label': 'Eligible dependant amount'},
 ('T1', '30425'): {'applicability': 'Schedule 5 infirm-dependant eligibility exists',
                   'label': 'Canada caregiver amount for spouse/dependant 18+'},
 ('T1', '30450'): {'applicability': 'Schedule 5 eligibility exists',
                   'label': 'Canada caregiver amount for other infirm dependants 18+'},
 ('T1', '30499'): {'applicability': 'Qualifying children exist; count line',
                   'label': 'Number of infirm children under 18 claimed'},
 ('T1', '30500'): {'applicability': 'Line 30499 count is positive',
                   'label': 'Canada caregiver amount for infirm children under 18'},
 ('T1', '30800'): {'applicability': 'Schedule 8/RC381 employment contribution exists',
                   'label': 'Base CPP/QPP contributions through employment'},
 ('T1', '31000'): {'applicability': 'Schedule 8/RC381 self-employment amount exists',
                   'label': 'Base CPP/QPP contributions on self-employment'},
 ('T1', '31200'): {'applicability': 'T4 EI premium exists, capped by form rule',
                   'label': 'EI premiums through employment'},
 ('T1', '31205'): {'applicability': 'T4 box 55 exists, capped by form rule',
                   'label': 'PPIP premiums paid'},
 ('T1', '31210'): {'applicability': 'Schedule 10 applies',
                   'label': 'PPIP premiums payable on employment'},
 ('T1', '31215'): {'applicability': 'Schedule 10 applies',
                   'label': 'PPIP premiums payable on self-employment'},
 ('T1', '31217'): {'applicability': 'Schedule 13 applies',
                   'label': 'EI premiums on self-employment'},
 ('T1', '31220'): {'applicability': 'Hours/eligibility election qualifies',
                   'label': "Volunteer firefighters' amount"},
 ('T1', '31240'): {'applicability': 'Hours/eligibility election qualifies',
                   'label': "Search and rescue volunteers' amount"},
 ('T1', '31260'): {'applicability': 'Employment income exists; lesser-of formula applies',
                   'label': 'Canada employment amount'},
 ('T1', '31270'): {'applicability': 'Qualifying acquisition exists',
                   'label': "Home buyers' amount"},
 ('T1', '31285'): {'applicability': 'Qualifying renovation exists',
                   'label': 'Home accessibility expenses'},
 ('T1', '31300'): {'applicability': 'Qualifying adoption period and expenses exist',
                   'label': 'Adoption expenses'},
 ('T1', '31400'): {'applicability': 'Eligible pension income exists',
                   'label': 'Pension income amount'},
 ('T1', '31600'): {'applicability': 'Approved DTC eligibility exists',
                   'label': 'Disability amount for self'},
 ('T1', '31800'): {'applicability': 'Eligible unused dependant amount is transferred',
                   'label': 'Disability amount transferred from dependant'},
 ('T1', '31900'): {'applicability': 'Qualifying government student-loan interest from 2025 or '
                                    'unused preceding five years is claimed',
                   'label': 'Student-loan interest'},
 ('T1', '32300'): {'applicability': 'Schedule 11 current/prior tuition claim exists',
                   'label': 'Federal tuition amount'},
 ('T1', '32400'): {'applicability': 'Valid transfer exists',
                   'label': 'Tuition transferred from child/grandchild'},
 ('T1', '32600'): {'applicability': 'Schedule 2 transfer exists',
                   'label': 'Amounts transferred from spouse/partner'},
 ('T1', '33099'): {'applicability': 'Eligible expenses exist',
                   'label': 'Medical expenses for self/family'},
 ('T1', '33199'): {'applicability': 'Eligible dependant expenses exist',
                   'label': 'Medical expenses for other dependants'},
 ('T1', '33200'): {'applicability': 'A medical-expense claim exists; calculate thresholds',
                   'label': 'Allowable medical expense total'},
 ('T1', '33500'): {'applicability': 'Always: applicable non-refundable amounts subtotal',
                   'label': 'Credit base'},
 ('T1', '33800'): {'applicability': 'Always: line 33500 times 14.5%', 'label': 'Credits at 14.5%'},
 ('T1', '34900'): {'applicability': 'Schedule 9 claim exists', 'label': 'Donations and gifts'},
 ('T1', '34990'): {'applicability': 'Federal Worksheet produces amount',
                   'label': 'Top-up tax credit'},
 ('T1', '35000'): {'applicability': 'Always', 'label': 'Total federal non-refundable tax credits'},
 ('T1', '40400'): {'applicability': 'Always: printed rows 123 + 124',
                   'label': 'Federal tax before credits'},
 ('T1', '40424'): {'applicability': 'T1206 applies', 'label': 'Federal tax on split income'},
 ('T1', '40425'): {'applicability': 'Taxable Canadian dividend exists',
                   'label': 'Federal dividend tax credit'},
 ('T1', '40427'): {'applicability': 'T691 produces an available amount',
                   'label': 'Minimum-tax carryover'},
 ('T1', '40500'): {'applicability': 'T2209 applies', 'label': 'Federal foreign tax credit'},
 ('T1', '40600'): {'applicability': 'Always after applicable surtax/recapture/logging rows',
                   'label': 'Federal tax'},
 ('T1', '40900'): {'applicability': 'Eligible receipts exist; information amount',
                   'label': 'Total federal political contributions'},
 ('T1', '41000'): {'applicability': 'Line 40900 exists; worksheet formula applies',
                   'label': 'Federal political contribution credit'},
 ('T1', '41200'): {'applicability': 'T2038(IND) applies', 'label': 'Investment tax credit'},
 ('T1', '41300'): {'applicability': 'Eligible shares exist; information amount',
                   'label': 'Net cost of labour-sponsored fund shares'},
 ('T1', '41400'): {'applicability': 'Line 41300 yields eligible credit',
                   'label': 'Labour-sponsored funds tax credit'},
 ('T1', '41500'): {'applicability': 'RC210/ACWB amount exists',
                   'label': 'Advanced Canada workers benefit'},
 ('T1', '41600'): {'applicability': 'Always: applicable lines 41000–41400',
                   'label': 'Total credits'},
 ('T1', '41700'): {'applicability': 'Always: non-negative result',
                   'label': 'Federal tax after credits'},
 ('T1', '41800'): {'applicability': 'A listed federal special tax applies',
                   'label': 'Special taxes'},
 ('T1', '42000'): {'applicability': 'Always', 'label': 'Net federal tax'},
 ('T1', '42120'): {'applicability': 'Schedule 13 applies',
                   'label': 'EI premiums payable on self-employment'},
 ('T1', '42200'): {'applicability': 'Line 23500 is positive', 'label': 'Social benefits repayment'},
 ('T1', '42800'): {'applicability': 'T2203 multi-jurisdiction calculation applies',
                   'label': 'Provincial/territorial tax'},
 ('T1', '42900'): {'applicability': 'Always: non-negative result after credits',
                   'label': 'Basic federal tax'},
 ('T1', '43500'): {'applicability': 'Always', 'label': 'Total payable'},
 ('T1', '43700'): {'applicability': 'Sum supported withholding slips; otherwise 0',
                   'label': 'Total income tax deducted'},
 ('T1', '43800'): {'applicability': 'Quebec resident with eligible federal withholding; statutory '
                                    'transfer formula applies',
                   'label': 'Tax transfer for residents of Quebec'},
 ('T1', '43850'): {'applicability': 'Always for Quebec return',
                   'label': 'Tax deducted after Quebec transfer'},
 ('T1', '44000'): {'applicability': 'Quebec resident; 16.5% of line 42900',
                   'label': 'Refundable Quebec abatement'},
 ('T1', '45000'): {'applicability': 'T4/Schedule 10 computation yields overpayment',
                   'label': 'EI overpayment'},
 ('T1', '45100'): {'applicability': 'Always after deducting line 31210; may be 0',
                   'label': 'Net EI overpayment'},
 ('T1', '45200'): {'applicability': 'Eligibility and worksheet thresholds apply',
                   'label': 'Refundable medical expense supplement'},
 ('T1', '45300'): {'applicability': 'Schedule 6 eligibility exists',
                   'label': 'Canada workers benefit'},
 ('T1', '45350'): {'applicability': 'Schedule 11 entitlement and eligible fees exist',
                   'label': 'Canada training credit'},
 ('T1', '45355'): {'applicability': 'Schedule 12 applies',
                   'label': 'Multigenerational home renovation credit'},
 ('T1', '45400'): {'applicability': 'T2038(IND) produces refund',
                   'label': 'Refund of investment tax credit'},
 ('T1', '45600'): {'applicability': 'T3 box 38/T5013 box 209 exists',
                   'label': 'Part XII.2 tax credit'},
 ('T1', '45700'): {'applicability': 'GST370 applies',
                   'label': 'Employee and partner GST/HST rebate'},
 ('T1', '46800'): {'applicability': 'Qualifying educator expenses exist; information amount',
                   'label': 'Eligible educator supplies expenses'},
 ('T1', '46900'): {'applicability': '25% of eligible line 46800, subject to cap',
                   'label': 'Eligible educator school-supply credit'},
 ('T1', '47555'): {'applicability': 'T5013 box 236 exists',
                   'label': 'Canadian journalism labour tax credit'},
 ('T1', '47556'): {'applicability': 'T2043 applies',
                   'label': 'Return of fuel charge proceeds to farmers credit'},
 ('T1', '47600'): {'applicability': 'CRA instalment payments exist',
                   'label': 'Tax paid by instalments'},
 ('T1', '48200'): {'applicability': 'Always', 'label': 'Total credits'},
 ('T1', '48400'): {'applicability': 'Always as one side of result; max(credits-payable, 0)',
                   'label': 'Refund'},
 ('T1', '48500'): {'applicability': 'Always as other side; max(payable-credits, 0)',
                   'label': 'Balance owing'},
 ('TP1', '100'): {'applicability': 'RL-1 box M exists; information line', 'label': 'Commissions'},
 ('TP1', '101'): {'applicability': 'RL-1 box A and supported corrections',
                  'label': 'Employment income'},
 ('TP1', '102'): {'applicability': 'RL-1 box L exists; information line',
                  'label': 'Taxable benefit included in employment income'},
 ('TP1', '105'): {'applicability': 'RL-22 less RL-1 box P work chart applies',
                  'label': 'Correction of employment income'},
 ('TP1', '106'): {'applicability': 'A guide-listed other employment category exists',
                  'label': 'Other employment income code / amount'},
 ('TP1', '107'): {'applicability': 'A guide-listed other employment category exists',
                  'label': 'Other employment income code / amount'},
 ('TP1', '110'): {'applicability': 'RL-6 amount exists', 'label': 'QPIP benefits'},
 ('TP1', '111'): {'applicability': 'T4E amount exists', 'label': 'Employment Insurance benefits'},
 ('TP1', '114'): {'applicability': 'T4A(OAS) amount exists', 'label': 'Old Age Security pension'},
 ('TP1', '119'): {'applicability': 'T4A(P) amount exists', 'label': 'CPP/QPP benefits'},
 ('TP1', '122'): {'applicability': 'Supported retirement income exists',
                  'label': 'Pensions, annuities and other amounts'},
 ('TP1', '123'): {'applicability': 'Joint election applies',
                  'label': 'Retirement income transferred by spouse'},
 ('TP1', '128'): {'applicability': 'Dividend gross-up calculation applies',
                  'label': 'Taxable dividends'},
 ('TP1', '130'): {'applicability': 'RL-3/T5 or accrued investment income exists',
                  'label': 'Interest and other investment income'},
 ('TP1', '136'): {'applicability': 'Rental activity exists and TP-128 applies',
                  'label': 'Gross / net rental income'},
 ('TP1', '139'): {'applicability': 'Disposition or capital-gain slip exists',
                  'label': 'Taxable capital gains'},
 ('TP1', '142'): {'applicability': 'Support was received and work chart yields taxable amount',
                  'label': 'Taxable support payments received'},
 ('TP1', '147'): {'applicability': 'RL-5/T5007 amount exists',
                  'label': 'Social assistance and similar financial assistance'},
 ('TP1', '148'): {'applicability': 'A guide-listed indemnity exists',
                  'label': 'Income-replacement indemnity code / amount'},
 ('TP1', '149'): {'applicability': 'A guide-listed indemnity exists',
                  'label': 'Income-replacement indemnity code / amount'},
 ('TP1', '153'): {'applicability': 'Guide-listed other income exists: code 01 ordinary '
                                   'scholarships; point 3 item 8 RESP EAP; or another supported '
                                   'category',
                  'label': 'Other income code / amount'},
 ('TP1', '154'): {'applicability': 'Guide-listed other income exists: code 01 ordinary '
                                   'scholarships; point 3 item 8 RESP EAP; or another supported '
                                   'category',
                  'label': 'Other income code / amount'},
 ('TP1', '164'): {'applicability': 'Schedule L/business activity exists',
                  'label': 'Business income'},
 ('TP1', '165'): {'applicability': 'Supported employee premium exists; information line',
                  'label': 'Wage-loss replacement plan premium'},
 ('TP1', '166'): {'applicability': 'RL-3/RL-15 actual dividend exists; information lines',
                  'label': 'Actual eligible / ordinary dividends'},
 ('TP1', '167'): {'applicability': 'RL-3/RL-15 actual dividend exists; information lines',
                  'label': 'Actual eligible / ordinary dividends'},
 ('TP1', '168'): {'applicability': 'Rental activity exists and TP-128 applies',
                  'label': 'Gross / net rental income'},
 ('TP1', '169'): {'applicability': 'Relevant T4A box amount exists; information line',
                  'label': 'Canada recovery benefits included on line 148'},
 ('TP1', '199'): {'applicability': 'Always', 'label': 'Total income'},
 ('TP1', '201'): {'applicability': 'Eligible work income exists; 6%, maximum $1,420',
                  'label': 'Deduction for workers'},
 ('TP1', '205'): {'applicability': 'RL-1 box D/receipt amount exists',
                  'label': 'Registered pension plan deduction'},
 ('TP1', '206'): {'applicability': 'Guide-listed employment expense exists',
                  'label': 'Employment-expense code / deduction'},
 ('TP1', '207'): {'applicability': 'Guide-listed employment expense exists',
                  'label': 'Employment-expense code / deduction'},
 ('TP1', '212'): {'applicability': 'RRSP Schedule 7 fact applies; information line',
                  'label': 'HBP/LLP repayment or contribution information'},
 ('TP1', '214'): {'applicability': 'Deductible contribution is claimed',
                  'label': 'RRSP/PRPP deduction'},
 ('TP1', '215'): {'applicability': 'Deductible FHSA contribution is claimed',
                  'label': 'FHSA deduction'},
 ('TP1', '225'): {'applicability': 'Support paid and work chart yields deductible amount',
                  'label': 'Deductible support payments'},
 ('TP1', '228'): {'applicability': 'Qualifying move exists', 'label': 'Moving expenses'},
 ('TP1', '231'): {'applicability': 'Qualifying investment expense exists',
                  'label': 'Carrying charges and interest expenses'},
 ('TP1', '233'): {'applicability': 'Qualifying loss exists',
                  'label': 'Total / allowable business investment loss'},
 ('TP1', '234'): {'applicability': 'Qualifying loss exists',
                  'label': 'Total / allowable business investment loss'},
 ('TP1', '236'): {'applicability': 'TP-350.1-V applies',
                  'label': 'Deduction for residents of designated remote areas'},
 ('TP1', '241'): {'applicability': 'Qualifying expenses exist',
                  'label': 'Exploration and development expenses'},
 ('TP1', '245'): {'applicability': 'Joint election applies',
                  'label': 'Retirement income transferred to spouse'},
 ('TP1', '246'): {'applicability': 'A guide-listed repayment exists',
                  'label': 'Deduction for amounts repaid'},
 ('TP1', '248'): {'applicability': 'QPP/QPIP/CPP schedule produces deductible amount',
                  'label': 'Contribution-deduction code / amount'},
 ('TP1', '248.1'): {'applicability': 'QPP/QPIP/CPP schedule produces deductible amount',
                    'label': 'Contribution-deduction code / amount'},
 ('TP1', '249'): {'applicability': 'A guide-listed other deduction exists',
                  'label': 'Other-deduction code / amount'},
 ('TP1', '250'): {'applicability': 'A guide-listed other deduction exists',
                  'label': 'Other-deduction code / amount'},
 ('TP1', '252'): {'applicability': 'Schedule N carryforward applies',
                  'label': 'Adjustment of investment expenses'},
 ('TP1', '254'): {'applicability': 'Always', 'label': 'Total deductions'},
 ('TP1', '256'): {'applicability': 'Always', 'label': 'Income after deductions'},
 ('TP1', '260'): {'applicability': 'A guide-listed adjustment exists',
                  'label': 'Adjustment of deductions'},
 ('TP1', '275'): {'applicability': 'Always', 'label': 'Net income'},
 ('TP1', '276'): {'applicability': 'A guide-listed adjustment exists',
                  'label': 'Net-income adjustment code / amount'},
 ('TP1', '277'): {'applicability': 'A guide-listed adjustment exists',
                  'label': 'Net-income adjustment code / amount'},
 ('TP1', '278'): {'applicability': 'Relevant income exists; information amount',
                  'label': 'UCCB/RDSP income included for family-benefit calculations'},
 ('TP1', '279'): {'applicability': 'Always', 'label': 'Adjusted net-income subtotal'},
 ('TP1', '286'): {'applicability': 'Qualifying program amount exists',
                  'label': 'Strategic-investment-program deduction code / amount'},
 ('TP1', '287'): {'applicability': 'Qualifying program amount exists',
                  'label': 'Strategic-investment-program deduction code / amount'},
 ('TP1', '289'): {'applicability': 'Available prior loss is claimed',
                  'label': 'Prior non-capital-loss code / amount'},
 ('TP1', '289.1'): {'applicability': 'Available prior loss is claimed',
                    'label': 'Prior non-capital-loss code / amount'},
 ('TP1', '290'): {'applicability': 'Available prior loss is claimed',
                  'label': 'Net capital loss from other years'},
 ('TP1', '291'): {'applicability': 'Qualifying event exists',
                  'label': 'Deduction for qualifying transfer/conversion gain'},
 ('TP1', '292'): {'applicability': 'Qualifying gain and TP-726.7-V calculation exist',
                  'label': 'Capital gains deduction'},
 ('TP1', '293'): {'applicability': 'A guide-listed category exists',
                  'label': 'Deduction for income not taxable under supported rule/treaty'},
 ('TP1', '295'): {'applicability': 'Included scholarship or another guide-listed amount qualifies; '
                                   'ordinary scholarship line 154 code 01 is generally mirrored '
                                   'here',
                  'label': 'Deduction for certain income'},
 ('TP1', '296'): {'applicability': 'A guide-listed category exists',
                  'label': 'Miscellaneous-deduction code / amount'},
 ('TP1', '297'): {'applicability': 'A guide-listed category exists',
                  'label': 'Miscellaneous-deduction code / amount'},
 ('TP1', '298'): {'applicability': 'Always', 'label': 'Total taxable-income deductions'},
 ('TP1', '299'): {'applicability': 'Always: max(line 279 less 298, 0)', 'label': 'Taxable income'},
 ('TP1', '350'): {'applicability': 'Always ($18,571 for 2025 form)',
                  'label': 'Basic personal amount'},
 ('TP1', '358'): {'applicability': 'A line-358 adjustment applies; otherwise 0',
                  'label': 'Adjustment for income-replacement indemnities'},
 ('TP1', '359'): {'applicability': 'Always: line 350 less line 358',
                  'label': 'Basic personal amount after line-358 adjustment'},
 ('TP1', '361'): {'applicability': 'Schedule B applies; living-alone eligibility is independent of '
                                   'solidarity-credit election',
                  'label': 'Age amount, amount for a person living alone and retirement-income '
                           'amount'},
 ('TP1', '367'): {'applicability': 'Schedule A applies',
                  'label': 'Amount for dependants and amount transferred by a child 18+ in '
                           'post-secondary studies'},
 ('TP1', '376'): {'applicability': 'Eligibility exists',
                  'label': 'Amount for a severe and prolonged impairment'},
 ('TP1', '377'): {'applicability': 'Always: add lines 359 through 376',
                  'label': 'Personal-amount subtotal'},
 ('TP1', '377.1'): {'applicability': 'Always: line 377 multiplied by 14%',
                    'label': 'Personal-amount credit at 14%'},
 ('TP1', '378'): {'applicability': 'TP-752.0.13.1-V applies',
                  'label': 'Expenses for medical services not available locally'},
 ('TP1', '381'): {'applicability': 'Schedule B medical-expense calculation applies',
                  'label': 'Medical expenses'},
 ('TP1', '385'): {'applicability': 'Schedule M claim exists, including prior unused balance',
                  'label': 'Interest paid on a student loan'},
 ('TP1', '388'): {'applicability': 'Always: add lines 378 through 385',
                  'label': 'Medical-and-student-interest subtotal'},
 ('TP1', '389'): {'applicability': 'Always: line 388 multiplied by 20%',
                  'label': 'Medical-and-student-interest credit at 20%'},
 ('TP1', '390'): {'applicability': 'Hours/eligibility election qualifies',
                  'label': 'Volunteer firefighter/search-and-rescue code / credit'},
 ('TP1', '390.1'): {'applicability': 'Hours/eligibility election qualifies',
                    'label': 'Volunteer firefighter/search-and-rescue code / credit'},
 ('TP1', '391'): {'applicability': 'TP-752.PC-V age and work-income rules apply',
                  'label': 'Tax credit for career extension'},
 ('TP1', '392'): {'applicability': 'TP-776.1.ND-V applies',
                  'label': 'Tax credit for recent graduates working in remote resource regions'},
 ('TP1', '393'): {'applicability': 'Work Chart 395 or Schedule V applies',
                  'label': 'Donations amount / tax credits'},
 ('TP1', '395'): {'applicability': 'Work Chart 395 or Schedule V applies',
                  'label': 'Donations amount / tax credits'},
 ('TP1', '396'): {'applicability': 'TP-752.HA-V applies', 'label': "Home buyers' tax credit"},
 ('TP1', '397'): {'applicability': 'Qualifying dues exist; 10% credit',
                  'label': 'Union, professional or other dues / credit'},
 ('TP1', '397.1'): {'applicability': 'Qualifying dues exist; 10% credit',
                    'label': 'Union, professional or other dues / credit'},
 ('TP1', '398'): {'applicability': 'Schedule T applies',
                  'label': 'Tax credit for tuition or examination fees'},
 ('TP1', '398.1'): {'applicability': 'Valid child transfer exists',
                    'label': 'Tuition or examination credit transferred by a child'},
 ('TP1', '399'): {'applicability': 'Always', 'label': 'Total non-refundable tax credits'},
 ('TP1', '401'): {'applicability': 'Always calculate line 401; line 403 marks Schedule E use',
                  'label': 'Schedule E indicator / tax on taxable income'},
 ('TP1', '403'): {'applicability': 'Always calculate line 401; line 403 marks Schedule E use',
                  'label': 'Schedule E indicator / tax on taxable income'},
 ('TP1', '404'): {'applicability': 'The corresponding TP-766.2-V calculation applies',
                  'label': 'Form TP-766.2-V indicators'},
 ('TP1', '405'): {'applicability': 'The corresponding TP-766.2-V calculation applies',
                  'label': 'Form TP-766.2-V indicators'},
 ('TP1', '406'): {'applicability': 'Always: copy line 399',
                  'label': 'Non-refundable tax credits carried from line 399'},
 ('TP1', '413'): {'applicability': 'Always', 'label': 'Tax after non-refundable credits'},
 ('TP1', '414'): {'applicability': 'Eligible contribution exists',
                  'label': 'Political contribution credit'},
 ('TP1', '415'): {'applicability': 'Taxable Québec dividend exists',
                  'label': 'Dividend tax credit'},
 ('TP1', '422'): {'applicability': 'Eligible RL-26 box B share purchase exists',
                  'label': 'Tax credit for acquisition of Capital régional shares'},
 ('TP1', '424'): {'applicability': 'Eligible fund share purchase exists',
                  'label': 'Tax credit for a labour-sponsored fund'},
 ('TP1', '425'): {'applicability': 'Always', 'label': 'Total credits from lines 414 through 424'},
 ('TP1', '430'): {'applicability': 'Always', 'label': 'Tax before credits'},
 ('TP1', '431'): {'applicability': 'Valid spouse transfer applies',
                  'label': 'Credits transferred between spouses'},
 ('TP1', '432'): {'applicability': 'Always', 'label': 'Income tax'},
 ('TP1', '438'): {'applicability': 'Line 436 says registered enterprise and fee is due',
                  'label': 'Annual registration fee for enterprise register'},
 ('TP1', '439'): {'applicability': 'Schedule R applies',
                  'label': 'QPIP premium on self-employment/outside-Québec work'},
 ('TP1', '441'): {'applicability': 'RL-19/RL-22/RL-31 or other supported advance exists',
                  'label': 'Advance payments of tax credits'},
 ('TP1', '442'): {'applicability': 'A guide-listed special tax applies, including excess QESI when '
                                   'triggered',
                  'label': 'Special-tax code / amount'},
 ('TP1', '443'): {'applicability': 'A guide-listed special tax applies, including excess QESI when '
                                   'triggered',
                  'label': 'Special-tax code / amount'},
 ('TP1', '444'): {'applicability': 'Schedule U/LE-35 yields contribution payable',
                  'label': 'Schedule U indicator / QPP contribution'},
 ('TP1', '445'): {'applicability': 'Schedule U/LE-35 yields contribution payable',
                  'label': 'Schedule U indicator / QPP contribution'},
 ('TP1', '446'): {'applicability': 'Schedule F income subject to contribution exceeds $18,130',
                  'label': 'Contribution to the health services fund'},
 ('TP1', '447'): {'applicability': 'Schedule K applies; coverage screen determines amount or '
                                   'explicit exemption',
                  'label': 'Prescription-drug-plan code / premium'},
 ('TP1', '449'): {'applicability': 'Schedule K applies; coverage screen determines amount or '
                                   'explicit exemption',
                  'label': 'Prescription-drug-plan code / premium'},
 ('TP1', '450'): {'applicability': 'Always', 'label': 'Total tax and contributions'},
 ('TP1', '451'): {'applicability': 'Sum RL-slip withholding; otherwise 0',
                  'label': 'Québec income tax withheld'},
 ('TP1', '451.1'): {'applicability': 'Valid spouse transfer applies',
                    'label': 'Income tax transferred by spouse'},
 ('TP1', '451.2'): {'applicability': 'Always', 'label': 'Net Québec income tax withheld'},
 ('TP1', '451.3'): {'applicability': 'Valid spouse transfer applies',
                    'label': 'Spouse withholding transferred'},
 ('TP1', '452'): {'applicability': 'Schedule U/LE-35 produces overpayment',
                  'label': 'QPP/CPP overpayment'},
 ('TP1', '453'): {'applicability': 'Québec instalment payments exist',
                  'label': 'Income tax paid by instalments'},
 ('TP1', '454'): {'applicability': 'Federal T2203/transfer circumstance applies',
                  'label': 'Tax transfer by resident of Québec'},
 ('TP1', '455'): {'applicability': 'Schedule C applies',
                  'label': 'Tax credit for childcare expenses'},
 ('TP1', '456'): {'applicability': 'Schedule P applies', 'label': 'Work-premium tax credits'},
 ('TP1', '457'): {'applicability': 'Employment/self-employment QPIP computation produces '
                                   'overpayment; if relevant earnings under $2,000, all line 97 is '
                                   'overpayment',
                  'label': 'QPIP overpayment'},
 ('TP1', '458'): {'applicability': 'Schedule J applies',
                  'label': 'Home-support-services tax credit for seniors'},
 ('TP1', '459'): {'applicability': 'VD-358-V applies',
                  'label': 'QST rebate for employees/partners'},
 ('TP1', '460'): {'applicability': 'TP-1029.BF-V eligibility exists', 'label': 'Tax shield'},
 ('TP1', '461'): {'applicability': 'A guide-listed refundable credit applies',
                  'label': 'Other refundable-credit code / amount'},
 ('TP1', '462'): {'applicability': 'A guide-listed refundable credit applies',
                  'label': 'Other refundable-credit code / amount'},
 ('TP1', '463'): {'applicability': 'Eligibility exists', 'label': 'Senior assistance amount'},
 ('TP1', '465'): {'applicability': 'Always', 'label': 'Total credits'},
 ('TP1', '466'): {'applicability': 'Protected-credit/work-chart circumstance applies',
                  'label': 'Financial compensation for home-support services'},
 ('TP1', '468'): {'applicability': 'Always', 'label': 'Refundable-credit total after compensation'},
 ('TP1', '470'): {'applicability': 'Always',
                  'label': 'Difference between tax/contributions and credits'},
 ('TP1', '474'): {'applicability': 'Always when credits exceed tax; otherwise 0',
                  'label': 'Refund before transfer'},
 ('TP1', '475'): {'applicability': 'Always when tax exceeds credits; otherwise 0',
                  'label': 'Balance due before transfer'},
 ('TP1', '476'): {'applicability': 'Valid election applies',
                  'label': 'Refund transferred to spouse'},
 ('TP1', '477'): {'applicability': 'Valid election applies',
                  'label': 'Balance transferred from spouse'},
 ('TP1', '478'): {'applicability': 'Always as one side of result', 'label': 'Refund'},
 ('TP1', '479'): {'applicability': 'Always as other side of result', 'label': 'Balance due'},
 ('TP1', '480'): {'applicability': 'Filing election; outside calculation packet',
                  'label': 'Accelerated refund requested'},
 ('TP1', '481'): {'applicability': 'Payment/filing field; outside calculation packet',
                  'label': 'Amount enclosed'},
 ('TP1', '96'): {'applicability': 'T4 CPP contribution exists', 'label': 'CPP contribution'},
 ('TP1', '96.1'): {'applicability': 'T4 CPP pensionable earnings exists',
                   'label': 'CPP pensionable earnings'},
 ('TP1', '96.2'): {'applicability': 'Schedule U/LE-35 calculation applies',
                   'label': 'Additional CPP contribution'},
 ('TP1', '97'): {'applicability': 'RL-1 box H exists', 'label': 'QPIP premium'},
 ('TP1', '98'): {'applicability': 'RL-1 box B exists', 'label': 'QPP contribution'},
 ('TP1', '98.1'): {'applicability': 'RL-1 box G exists', 'label': 'QPP pensionable salary/wages'},
 ('TP1', '98.2'): {'applicability': 'Schedule U/LE-35 calculation applies',
                   'label': 'Additional QPP contribution'}}

def official_line_label(form_id: str, line_id: str) -> str | None:
    entry = LINE_LABELS_2025.get((form_id, line_id))
    return None if entry is None else entry["label"]

def official_applicability(form_id: str, line_id: str) -> str | None:
    entry = LINE_LABELS_2025.get((form_id, line_id))
    return None if entry is None else entry["applicability"]
# Federal printed rows 71-172 from CRA 2025 5005-R E pages 5-8.
LINE_LABELS_2025.update(
{('T1', '100'): {'applicability': 'Always: subtotal of printed rows 87 through 99',
                 'label': 'Add lines 87 to 99'},
 ('T1', '101'): {'applicability': 'Printed carry of line 31400', 'label': 'Pension income amount'},
 ('T1', '102'): {'applicability': 'Always: subtotal of printed rows 86, 100, and 101',
                 'label': 'Add lines 86, 100, and 101'},
 ('T1', '103'): {'applicability': 'Printed carry of line 31600',
                 'label': 'Disability amount for self'},
 ('T1', '104'): {'applicability': 'Printed carry of line 31800',
                 'label': 'Disability amount transferred from a dependant'},
 ('T1', '105'): {'applicability': 'Always: subtotal of printed rows 102 through 104',
                 'label': 'Add lines 102 to 104'},
 ('T1', '106'): {'applicability': 'Printed carry of line 31900',
                 'label': 'Interest paid on your student loans'},
 ('T1', '107'): {'applicability': 'Printed carry of line 32300',
                 'label': 'Your federal tuition amount'},
 ('T1', '108'): {'applicability': 'Printed carry of line 32400',
                 'label': 'Tuition amount transferred from a child or grandchild'},
 ('T1', '109'): {'applicability': 'Printed carry of line 32600',
                 'label': 'Amounts transferred from your spouse or common-law partner'},
 ('T1', '110'): {'applicability': 'Always: subtotal of printed rows 105 through 109',
                 'label': 'Add lines 105 to 109'},
 ('T1', '111'): {'applicability': 'Printed carry of line 33099',
                 'label': 'Medical expenses for self, spouse or common-law partner, and dependent '
                          'children under 18'},
 ('T1', '112'): {'applicability': 'Always: medical-expense threshold calculation row',
                 'label': 'Amount from line 23600 multiplied by 3%'},
 ('T1', '113'): {'applicability': 'Always: medical-expense threshold limit',
                 'label': 'Lesser of $2,834 or the amount from line 112'},
 ('T1', '114'): {'applicability': 'Always: cannot be negative', 'label': 'Line 111 minus line 113'},
 ('T1', '115'): {'applicability': 'Printed carry of line 33199',
                 'label': 'Allowable amount of medical expenses for other dependants'},
 ('T1', '116'): {'applicability': 'Printed carry of line 33200', 'label': 'Line 114 plus line 115'},
 ('T1', '117'): {'applicability': 'Printed carry of line 33500', 'label': 'Line 110 plus line 116'},
 ('T1', '118'): {'applicability': 'Always: printed federal credit rate',
                 'label': 'Federal non-refundable tax credit rate'},
 ('T1', '119'): {'applicability': 'Printed carry of line 33800',
                 'label': 'Line 117 multiplied by the percentage from line 118'},
 ('T1', '120'): {'applicability': 'Printed carry of line 34900', 'label': 'Donations and gifts'},
 ('T1', '121'): {'applicability': 'Printed carry of line 34990', 'label': 'Top-up tax credit'},
 ('T1', '122'): {'applicability': 'Always: add lines 119 to 121; printed carry of line 35000',
                 'label': 'Total federal non-refundable tax credits'},
 ('T1', '123'): {'applicability': 'Always: carry printed row 77', 'label': 'Amount from line 77'},
 ('T1', '124'): {'applicability': 'Printed carry of line 40424',
                 'label': 'Federal tax on split income'},
 ('T1', '125'): {'applicability': 'Printed carry of line 40400', 'label': 'Line 123 plus line 124'},
 ('T1', '126'): {'applicability': 'Always: carry total federal non-refundable tax credits',
                 'label': 'Amount from line 35000'},
 ('T1', '127'): {'applicability': 'Printed carry of line 40425',
                 'label': 'Federal dividend tax credit'},
 ('T1', '128'): {'applicability': 'Printed carry of line 40427', 'label': 'Minimum tax carryover'},
 ('T1', '129'): {'applicability': 'Always: subtotal before basic federal tax',
                 'label': 'Add lines 126 to 128'},
 ('T1', '130'): {'applicability': 'Always: line 125 minus line 129, if negative enter zero',
                 'label': 'Basic federal tax'},
 ('T1', '131'): {'applicability': 'Applies when Form T2203 applies; otherwise printed zero',
                 'label': 'Federal surtax on income earned outside Canada'},
 ('T1', '132'): {'applicability': 'Always: subtotal before foreign tax credit',
                 'label': 'Line 130 plus line 131'},
 ('T1', '133'): {'applicability': 'Printed carry of line 40500',
                 'label': 'Federal foreign tax credit'},
 ('T1', '134'): {'applicability': 'Always: subtotal after federal foreign tax credit',
                 'label': 'Line 132 minus line 133'},
 ('T1', '135'): {'applicability': 'Applies when Form T2038(IND) recapture applies; otherwise '
                                  'printed zero',
                 'label': 'Recapture of investment tax credit'},
 ('T1', '136'): {'applicability': 'Always: subtotal after recapture of investment tax credit',
                 'label': 'Line 134 plus line 135'},
 ('T1', '137'): {'applicability': 'Applies when federal logging tax credit exists; otherwise '
                                  'printed zero',
                 'label': 'Federal logging tax credit'},
 ('T1', '138'): {'applicability': 'Always: line 136 minus line 137, if negative enter zero',
                 'label': 'Federal tax'},
 ('T1', '139'): {'applicability': 'Printed carry of line 41000',
                 'label': 'Federal political contribution tax credit'},
 ('T1', '140'): {'applicability': 'Printed carry of line 41200', 'label': 'Investment tax credit'},
 ('T1', '141'): {'applicability': 'Printed carry of line 41400',
                 'label': 'Labour-sponsored funds tax credit'},
 ('T1', '142'): {'applicability': 'Printed carry of line 41600', 'label': 'Add lines 139 to 141'},
 ('T1', '143'): {'applicability': 'Printed carry of line 41700',
                 'label': 'Line 138 minus line 142'},
 ('T1', '144'): {'applicability': 'Printed carry of line 41500',
                 'label': 'Advanced Canada workers benefit'},
 ('T1', '145'): {'applicability': 'Printed carry of line 41800', 'label': 'Special taxes'},
 ('T1', '146'): {'applicability': 'Always: add lines 143 to 145; printed carry of line 42000',
                 'label': 'Net federal tax'},
 ('T1', '147'): {'applicability': 'Always: carry net federal tax',
                 'label': 'Amount from line 42000'},
 ('T1', '148'): {'applicability': 'Printed carry of line 42120',
                 'label': 'Employment insurance premiums payable on self-employment and other '
                          'eligible earnings'},
 ('T1', '149'): {'applicability': 'Printed carry of line 42200',
                 'label': 'Social benefits repayment'},
 ('T1', '150'): {'applicability': 'Printed carry of line 42800',
                 'label': 'Provincial or territorial tax'},
 ('T1', '151'): {'applicability': 'Always: add lines 147 to 150; printed carry of line 43500',
                 'label': 'Total payable'},
 ('T1', '152'): {'applicability': 'Always: carry total payable',
                 'label': 'Amount from line 151 of the previous page'},
 ('T1', '153'): {'applicability': 'Printed carry of line 43700',
                 'label': 'Total income tax deducted'},
 ('T1', '154'): {'applicability': 'Printed carry of line 43800',
                 'label': 'Tax transfer for residents of Quebec'},
 ('T1', '155'): {'applicability': 'Printed carry of line 43850',
                 'label': 'Line 153 minus line 154'},
 ('T1', '156'): {'applicability': 'Printed carry of line 44000',
                 'label': 'Refundable Quebec abatement'},
 ('T1', '157'): {'applicability': 'Printed carry of line 45000',
                 'label': 'Employment insurance overpayment'},
 ('T1', '158'): {'applicability': 'Always: carry line 31210 for net EI overpayment',
                 'label': 'Amount from line 31210'},
 ('T1', '159'): {'applicability': 'Printed carry of line 45100', 'label': 'Net EI overpayment'},
 ('T1', '160'): {'applicability': 'Printed carry of line 45200',
                 'label': 'Refundable medical expense supplement'},
 ('T1', '161'): {'applicability': 'Printed carry of line 45300', 'label': 'Canada workers benefit'},
 ('T1', '162'): {'applicability': 'Printed carry of line 45350', 'label': 'Canada training credit'},
 ('T1', '163'): {'applicability': 'Printed carry of line 45355',
                 'label': 'Multigenerational home renovation tax credit'},
 ('T1', '164'): {'applicability': 'Printed carry of line 45400',
                 'label': 'Refund of investment tax credit'},
 ('T1', '165'): {'applicability': 'Printed carry of line 45600', 'label': 'Part XII.2 tax credit'},
 ('T1', '166'): {'applicability': 'Printed carry of line 45700',
                 'label': 'Employee and partner GST/HST rebate'},
 ('T1', '167'): {'applicability': 'Printed carry of line 46900',
                 'label': 'Eligible educator school supply tax credit'},
 ('T1', '168'): {'applicability': 'Printed carry of line 47555',
                 'label': 'Canadian journalism labour tax credit'},
 ('T1', '169'): {'applicability': 'Printed carry of line 47556',
                 'label': 'Return of fuel charge proceeds to farmers tax credit'},
 ('T1', '170'): {'applicability': 'Printed carry of line 47600',
                 'label': 'Tax paid by instalments'},
 ('T1', '171'): {'applicability': 'Always: add lines 155, 156, and 159 to 170; printed carry of '
                                  'line 48200',
                 'label': 'Total credits'},
 ('T1', '172'): {'applicability': 'Always: line 152 minus line 171',
                 'label': 'Refund or balance owing'},
 ('T1', '71'): {'applicability': 'Always: use the amount from line 26000 to calculate federal tax '
                                 'on taxable income',
                'label': 'Amount from line 26000'},
 ('T1', '72'): {'applicability': 'Always: threshold from the applicable taxable-income column',
                'label': 'Federal tax bracket threshold'},
 ('T1', '73'): {'applicability': 'Always: cannot be negative', 'label': 'Line 71 minus line 72'},
 ('T1', '74'): {'applicability': 'Always: percentage from the applicable taxable-income column',
                'label': 'Federal tax bracket percentage'},
 ('T1', '75'): {'applicability': 'Always: bracket product',
                'label': 'Line 73 multiplied by the percentage from line 74'},
 ('T1', '76'): {'applicability': 'Always: base amount from the applicable taxable-income column',
                'label': 'Base tax from the applicable taxable-income column'},
 ('T1', '77'): {'applicability': 'Always: line 75 plus line 76',
                'label': 'Federal tax on taxable income'},
 ('T1', '78'): {'applicability': 'Always: printed carry of line 30000',
                'label': 'Basic personal amount'},
 ('T1', '79'): {'applicability': 'Printed carry of line 30100', 'label': 'Age amount'},
 ('T1', '80'): {'applicability': 'Printed carry of line 30300',
                'label': 'Spouse or common-law partner amount'},
 ('T1', '81'): {'applicability': 'Printed carry of line 30400',
                'label': 'Amount for an eligible dependant'},
 ('T1', '82'): {'applicability': 'Printed carry of line 30425',
                'label': 'Canada caregiver amount for spouse or common-law partner, or eligible '
                         'dependant age 18 or older'},
 ('T1', '83'): {'applicability': 'Printed carry of line 30450',
                'label': 'Canada caregiver amount for other infirm dependants age 18 or older'},
 ('T1', '84'): {'applicability': 'Printed carry of line 30500',
                'label': 'Canada caregiver amount for infirm children under 18 years of age'},
 ('T1', '85'): {'applicability': 'Always: subtotal of printed rows 78 through 84',
                'label': 'Add lines 78 to 84'},
 ('T1', '86'): {'applicability': 'Always: carry printed row 85',
                'label': 'Amount from line 85 of the previous page'},
 ('T1', '87'): {'applicability': 'Printed carry of line 30800',
                'label': 'Base CPP or QPP contributions through employment income'},
 ('T1', '88'): {'applicability': 'Printed carry of line 31000',
                'label': 'Base CPP or QPP contributions on self-employment income and other '
                         'earnings'},
 ('T1', '89'): {'applicability': 'Printed carry of line 31200',
                'label': 'Employment insurance premiums through employment'},
 ('T1', '90'): {'applicability': 'Printed carry of line 31217',
                'label': 'Employment insurance premiums on self-employment and other eligible '
                         'earnings'},
 ('T1', '91'): {'applicability': 'Printed carry of line 31205',
                'label': 'Provincial parental insurance plan premiums paid'},
 ('T1', '92'): {'applicability': 'Printed carry of line 31210',
                'label': 'PPIP premiums payable on employment income'},
 ('T1', '93'): {'applicability': 'Printed carry of line 31215',
                'label': 'PPIP premiums payable on self-employment income'},
 ('T1', '94'): {'applicability': 'Printed carry of line 31220',
                'label': "Volunteer firefighters' amount"},
 ('T1', '95'): {'applicability': 'Printed carry of line 31240',
                'label': "Search and rescue volunteers' amount"},
 ('T1', '96'): {'applicability': 'Printed carry of line 31260',
                'label': 'Canada employment amount'},
 ('T1', '97'): {'applicability': 'Printed carry of line 31270', 'label': "Home buyers' amount"},
 ('T1', '98'): {'applicability': 'Printed carry of line 31285',
                'label': 'Home accessibility expenses'},
 ('T1', '99'): {'applicability': 'Printed carry of line 31300', 'label': 'Adoption expenses'}}
)
